// This is a Vite app, not Next. The config it carried imported
// eslint-config-next, which is not a dependency here, so `npm run lint` failed
// to start at all - meaning nothing had been linted for as long as that was
// true.
import js from "@eslint/js"
import globals from "globals"
import reactHooks from "eslint-plugin-react-hooks"
import reactRefresh from "eslint-plugin-react-refresh"
import tseslint from "typescript-eslint"
import { globalIgnores } from "eslint/config"

export default tseslint.config([
  globalIgnores([
    "dist/**",
    // Generated by the TanStack Router plugin on every build.
    "src/routeTree.gen.ts",
    // shadcn/ui output, regenerated by the CLI rather than edited.
    "src/components/ui/**",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      // The plugins' own flat-config entries. react-hooks exports them under
      // configs.flat; react-refresh has no preset, so its rule is set below.
      reactHooks.configs.flat["recommended-latest"],
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: { "react-refresh": reactRefresh },
    rules: {
      // react-hooks 7 added compiler-driven rules that flag long-standing
      // patterns here: state set from an effect, and refs read during render.
      // They are worth reading, but as warnings - turning 23 existing call
      // sites into errors would stop CI on code that works, and the fix is a
      // refactor per site rather than a sweep.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      // Vite's fast refresh only works when a module exports components alone.
      // A warning, not an error: a route file exporting its Route constant
      // beside its component is how TanStack Router works.
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // An unused argument named with a leading underscore is a signature being
      // honoured, not a mistake.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Playwright fixtures take a function called `use`, which the hooks rules
    // read as a React hook called outside a component.
    files: ["e2e/**/*.ts", "playwright.config.ts"],
    rules: { "react-hooks/rules-of-hooks": "off" },
    languageOptions: { globals: globals.node },
  },
  {
    // Every route file exports its Route constant beside its component, which
    // is how TanStack Router works - not a mistake to warn about on every file
    // in the app.
    files: ["src/routes/**/*.tsx"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  {
    // The mock server answers arbitrary shapes, and typing every fixture as it
    // is would obscure what each handler is actually demonstrating.
    files: ["src/mocks/**/*.ts"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
])
