/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppNodesIndexRouteImport } from './routes/_app/nodes/index'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app/integrations/index'
import { Route as AppClusterIndexRouteImport } from './routes/_app/cluster/index'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppNodesIdRouteImport } from './routes/_app/nodes/$id'
import { Route as AppIntegrationsNewRouteImport } from './routes/_app/integrations/new'
import { Route as AppProjectsIdRouteRouteImport } from './routes/_app/projects/$id/route'
import { Route as AppProjectsIdIndexRouteImport } from './routes/_app/projects/$id/index'
import { Route as AppProjectsIdSettingsRouteImport } from './routes/_app/projects/$id/settings'
import { Route as AppProjectsIdRoutesRouteImport } from './routes/_app/projects/$id/routes'
import { Route as AppProjectsIdPipelinesRouteImport } from './routes/_app/projects/$id/pipelines'
import { Route as AppProjectsIdNewRouteImport } from './routes/_app/projects/$id/new'
import { Route as AppProjectsIdDatabasesRouteImport } from './routes/_app/projects/$id/databases'
import { Route as AppProjectsIdVolumesIndexRouteImport } from './routes/_app/projects/$id/volumes/index'
import { Route as AppProjectsIdStacksIndexRouteImport } from './routes/_app/projects/$id/stacks/index'
import { Route as AppProjectsIdServicesIndexRouteImport } from './routes/_app/projects/$id/services/index'
import { Route as AppProjectsIdSecretsIndexRouteImport } from './routes/_app/projects/$id/secrets/index'
import { Route as AppProjectsIdRoutesIndexRouteImport } from './routes/_app/projects/$id/routes/index'
import { Route as AppProjectsIdJobsIndexRouteImport } from './routes/_app/projects/$id/jobs/index'
import { Route as AppProjectsIdVolumesVolumeIdRouteImport } from './routes/_app/projects/$id/volumes/$volumeId'
import { Route as AppProjectsIdRoutesRouteIdRouteImport } from './routes/_app/projects/$id/routes/$routeId'
import { Route as AppProjectsIdJobsJobIdRouteImport } from './routes/_app/projects/$id/jobs/$jobId'
import { Route as AppProjectsIdStacksStackIdRouteRouteImport } from './routes/_app/projects/$id/stacks/$stackId/route'
import { Route as AppProjectsIdServicesServiceIdRouteRouteImport } from './routes/_app/projects/$id/services/$serviceId/route'
import { Route as AppProjectsIdStacksStackIdIndexRouteImport } from './routes/_app/projects/$id/stacks/$stackId/index'
import { Route as AppProjectsIdServicesServiceIdIndexRouteImport } from './routes/_app/projects/$id/services/$serviceId/index'
import { Route as AppProjectsIdStacksStackIdServicesRouteImport } from './routes/_app/projects/$id/stacks/$stackId/services'
import { Route as AppProjectsIdStacksStackIdEditorRouteImport } from './routes/_app/projects/$id/stacks/$stackId/editor'
import { Route as AppProjectsIdServicesServiceIdSettingsRouteImport } from './routes/_app/projects/$id/services/$serviceId/settings'
import { Route as AppProjectsIdServicesServiceIdOverviewRouteImport } from './routes/_app/projects/$id/services/$serviceId/overview'
import { Route as AppProjectsIdServicesServiceIdLogsRouteImport } from './routes/_app/projects/$id/services/$serviceId/logs'
import { Route as AppProjectsIdServicesServiceIdConfigRouteImport } from './routes/_app/projects/$id/services/$serviceId/config'
import { Route as AppProjectsIdServicesServiceIdBackupsRouteImport } from './routes/_app/projects/$id/services/$serviceId/backups'
import { Route as AppProjectsIdServicesServiceIdDeploymentsIndexRouteImport } from './routes/_app/projects/$id/services/$serviceId/deployments/index'
import { Route as AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRouteImport } from './routes/_app/projects/$id/services/$serviceId/deployments/$deploymentId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIndexRoute = AppNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const AppClusterIndexRoute = AppClusterIndexRouteImport.update({
  id: '/cluster/',
  path: '/cluster/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIdRoute = AppNodesIdRouteImport.update({
  id: '/nodes/$id',
  path: '/nodes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsNewRoute = AppIntegrationsNewRouteImport.update({
  id: '/integrations/new',
  path: '/integrations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRouteRoute = AppProjectsIdRouteRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdSettingsRoute = AppProjectsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdRoutesRoute = AppProjectsIdRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdPipelinesRoute = AppProjectsIdPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdNewRoute = AppProjectsIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdDatabasesRoute = AppProjectsIdDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdVolumesIndexRoute =
  AppProjectsIdVolumesIndexRouteImport.update({
    id: '/volumes/',
    path: '/volumes/',
    getParentRoute: () => AppProjectsIdRouteRoute,
  } as any)
const AppProjectsIdStacksIndexRoute =
  AppProjectsIdStacksIndexRouteImport.update({
    id: '/stacks/',
    path: '/stacks/',
    getParentRoute: () => AppProjectsIdRouteRoute,
  } as any)
const AppProjectsIdServicesIndexRoute =
  AppProjectsIdServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AppProjectsIdRouteRoute,
  } as any)
const AppProjectsIdSecretsIndexRoute =
  AppProjectsIdSecretsIndexRouteImport.update({
    id: '/secrets/',
    path: '/secrets/',
    getParentRoute: () => AppProjectsIdRouteRoute,
  } as any)
const AppProjectsIdRoutesIndexRoute =
  AppProjectsIdRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdRoutesRoute,
  } as any)
const AppProjectsIdJobsIndexRoute = AppProjectsIdJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdVolumesVolumeIdRoute =
  AppProjectsIdVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AppProjectsIdRouteRoute,
  } as any)
const AppProjectsIdRoutesRouteIdRoute =
  AppProjectsIdRoutesRouteIdRouteImport.update({
    id: '/$routeId',
    path: '/$routeId',
    getParentRoute: () => AppProjectsIdRoutesRoute,
  } as any)
const AppProjectsIdJobsJobIdRoute = AppProjectsIdJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppProjectsIdRouteRoute,
} as any)
const AppProjectsIdStacksStackIdRouteRoute =
  AppProjectsIdStacksStackIdRouteRouteImport.update({
    id: '/stacks/$stackId',
    path: '/stacks/$stackId',
    getParentRoute: () => AppProjectsIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdRouteRoute =
  AppProjectsIdServicesServiceIdRouteRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AppProjectsIdRouteRoute,
  } as any)
const AppProjectsIdStacksStackIdIndexRoute =
  AppProjectsIdStacksStackIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdStacksStackIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdIndexRoute =
  AppProjectsIdServicesServiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)
const AppProjectsIdStacksStackIdServicesRoute =
  AppProjectsIdStacksStackIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AppProjectsIdStacksStackIdRouteRoute,
  } as any)
const AppProjectsIdStacksStackIdEditorRoute =
  AppProjectsIdStacksStackIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AppProjectsIdStacksStackIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdSettingsRoute =
  AppProjectsIdServicesServiceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdOverviewRoute =
  AppProjectsIdServicesServiceIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdLogsRoute =
  AppProjectsIdServicesServiceIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdConfigRoute =
  AppProjectsIdServicesServiceIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdBackupsRoute =
  AppProjectsIdServicesServiceIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdDeploymentsIndexRoute =
  AppProjectsIdServicesServiceIdDeploymentsIndexRouteImport.update({
    id: '/deployments/',
    path: '/deployments/',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)
const AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute =
  AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRouteImport.update({
    id: '/deployments/$deploymentId',
    path: '/deployments/$deploymentId',
    getParentRoute: () => AppProjectsIdServicesServiceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/projects/$id': typeof AppProjectsIdRouteRouteWithChildren
  '/integrations/new': typeof AppIntegrationsNewRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/cluster/': typeof AppClusterIndexRoute
  '/integrations/': typeof AppIntegrationsIndexRoute
  '/nodes/': typeof AppNodesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/projects/$id/databases': typeof AppProjectsIdDatabasesRoute
  '/projects/$id/new': typeof AppProjectsIdNewRoute
  '/projects/$id/pipelines': typeof AppProjectsIdPipelinesRoute
  '/projects/$id/routes': typeof AppProjectsIdRoutesRouteWithChildren
  '/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/projects/$id/': typeof AppProjectsIdIndexRoute
  '/projects/$id/services/$serviceId': typeof AppProjectsIdServicesServiceIdRouteRouteWithChildren
  '/projects/$id/stacks/$stackId': typeof AppProjectsIdStacksStackIdRouteRouteWithChildren
  '/projects/$id/jobs/$jobId': typeof AppProjectsIdJobsJobIdRoute
  '/projects/$id/routes/$routeId': typeof AppProjectsIdRoutesRouteIdRoute
  '/projects/$id/volumes/$volumeId': typeof AppProjectsIdVolumesVolumeIdRoute
  '/projects/$id/jobs/': typeof AppProjectsIdJobsIndexRoute
  '/projects/$id/routes/': typeof AppProjectsIdRoutesIndexRoute
  '/projects/$id/secrets/': typeof AppProjectsIdSecretsIndexRoute
  '/projects/$id/services/': typeof AppProjectsIdServicesIndexRoute
  '/projects/$id/stacks/': typeof AppProjectsIdStacksIndexRoute
  '/projects/$id/volumes/': typeof AppProjectsIdVolumesIndexRoute
  '/projects/$id/services/$serviceId/backups': typeof AppProjectsIdServicesServiceIdBackupsRoute
  '/projects/$id/services/$serviceId/config': typeof AppProjectsIdServicesServiceIdConfigRoute
  '/projects/$id/services/$serviceId/logs': typeof AppProjectsIdServicesServiceIdLogsRoute
  '/projects/$id/services/$serviceId/overview': typeof AppProjectsIdServicesServiceIdOverviewRoute
  '/projects/$id/services/$serviceId/settings': typeof AppProjectsIdServicesServiceIdSettingsRoute
  '/projects/$id/stacks/$stackId/editor': typeof AppProjectsIdStacksStackIdEditorRoute
  '/projects/$id/stacks/$stackId/services': typeof AppProjectsIdStacksStackIdServicesRoute
  '/projects/$id/services/$serviceId/': typeof AppProjectsIdServicesServiceIdIndexRoute
  '/projects/$id/stacks/$stackId/': typeof AppProjectsIdStacksStackIdIndexRoute
  '/projects/$id/services/$serviceId/deployments/$deploymentId': typeof AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute
  '/projects/$id/services/$serviceId/deployments/': typeof AppProjectsIdServicesServiceIdDeploymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/integrations/new': typeof AppIntegrationsNewRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/cluster': typeof AppClusterIndexRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/nodes': typeof AppNodesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/projects/$id/databases': typeof AppProjectsIdDatabasesRoute
  '/projects/$id/new': typeof AppProjectsIdNewRoute
  '/projects/$id/pipelines': typeof AppProjectsIdPipelinesRoute
  '/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/projects/$id': typeof AppProjectsIdIndexRoute
  '/projects/$id/jobs/$jobId': typeof AppProjectsIdJobsJobIdRoute
  '/projects/$id/routes/$routeId': typeof AppProjectsIdRoutesRouteIdRoute
  '/projects/$id/volumes/$volumeId': typeof AppProjectsIdVolumesVolumeIdRoute
  '/projects/$id/jobs': typeof AppProjectsIdJobsIndexRoute
  '/projects/$id/routes': typeof AppProjectsIdRoutesIndexRoute
  '/projects/$id/secrets': typeof AppProjectsIdSecretsIndexRoute
  '/projects/$id/services': typeof AppProjectsIdServicesIndexRoute
  '/projects/$id/stacks': typeof AppProjectsIdStacksIndexRoute
  '/projects/$id/volumes': typeof AppProjectsIdVolumesIndexRoute
  '/projects/$id/services/$serviceId/backups': typeof AppProjectsIdServicesServiceIdBackupsRoute
  '/projects/$id/services/$serviceId/config': typeof AppProjectsIdServicesServiceIdConfigRoute
  '/projects/$id/services/$serviceId/logs': typeof AppProjectsIdServicesServiceIdLogsRoute
  '/projects/$id/services/$serviceId/overview': typeof AppProjectsIdServicesServiceIdOverviewRoute
  '/projects/$id/services/$serviceId/settings': typeof AppProjectsIdServicesServiceIdSettingsRoute
  '/projects/$id/stacks/$stackId/editor': typeof AppProjectsIdStacksStackIdEditorRoute
  '/projects/$id/stacks/$stackId/services': typeof AppProjectsIdStacksStackIdServicesRoute
  '/projects/$id/services/$serviceId': typeof AppProjectsIdServicesServiceIdIndexRoute
  '/projects/$id/stacks/$stackId': typeof AppProjectsIdStacksStackIdIndexRoute
  '/projects/$id/services/$serviceId/deployments/$deploymentId': typeof AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute
  '/projects/$id/services/$serviceId/deployments': typeof AppProjectsIdServicesServiceIdDeploymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$id': typeof AppProjectsIdRouteRouteWithChildren
  '/_app/integrations/new': typeof AppIntegrationsNewRoute
  '/_app/nodes/$id': typeof AppNodesIdRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/cluster/': typeof AppClusterIndexRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/nodes/': typeof AppNodesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/projects/$id/databases': typeof AppProjectsIdDatabasesRoute
  '/_app/projects/$id/new': typeof AppProjectsIdNewRoute
  '/_app/projects/$id/pipelines': typeof AppProjectsIdPipelinesRoute
  '/_app/projects/$id/routes': typeof AppProjectsIdRoutesRouteWithChildren
  '/_app/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/_app/projects/$id/': typeof AppProjectsIdIndexRoute
  '/_app/projects/$id/services/$serviceId': typeof AppProjectsIdServicesServiceIdRouteRouteWithChildren
  '/_app/projects/$id/stacks/$stackId': typeof AppProjectsIdStacksStackIdRouteRouteWithChildren
  '/_app/projects/$id/jobs/$jobId': typeof AppProjectsIdJobsJobIdRoute
  '/_app/projects/$id/routes/$routeId': typeof AppProjectsIdRoutesRouteIdRoute
  '/_app/projects/$id/volumes/$volumeId': typeof AppProjectsIdVolumesVolumeIdRoute
  '/_app/projects/$id/jobs/': typeof AppProjectsIdJobsIndexRoute
  '/_app/projects/$id/routes/': typeof AppProjectsIdRoutesIndexRoute
  '/_app/projects/$id/secrets/': typeof AppProjectsIdSecretsIndexRoute
  '/_app/projects/$id/services/': typeof AppProjectsIdServicesIndexRoute
  '/_app/projects/$id/stacks/': typeof AppProjectsIdStacksIndexRoute
  '/_app/projects/$id/volumes/': typeof AppProjectsIdVolumesIndexRoute
  '/_app/projects/$id/services/$serviceId/backups': typeof AppProjectsIdServicesServiceIdBackupsRoute
  '/_app/projects/$id/services/$serviceId/config': typeof AppProjectsIdServicesServiceIdConfigRoute
  '/_app/projects/$id/services/$serviceId/logs': typeof AppProjectsIdServicesServiceIdLogsRoute
  '/_app/projects/$id/services/$serviceId/overview': typeof AppProjectsIdServicesServiceIdOverviewRoute
  '/_app/projects/$id/services/$serviceId/settings': typeof AppProjectsIdServicesServiceIdSettingsRoute
  '/_app/projects/$id/stacks/$stackId/editor': typeof AppProjectsIdStacksStackIdEditorRoute
  '/_app/projects/$id/stacks/$stackId/services': typeof AppProjectsIdStacksStackIdServicesRoute
  '/_app/projects/$id/services/$serviceId/': typeof AppProjectsIdServicesServiceIdIndexRoute
  '/_app/projects/$id/stacks/$stackId/': typeof AppProjectsIdStacksStackIdIndexRoute
  '/_app/projects/$id/services/$serviceId/deployments/$deploymentId': typeof AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute
  '/_app/projects/$id/services/$serviceId/deployments/': typeof AppProjectsIdServicesServiceIdDeploymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/projects/$id'
    | '/integrations/new'
    | '/nodes/$id'
    | '/projects/new'
    | '/cluster/'
    | '/integrations/'
    | '/nodes/'
    | '/projects/'
    | '/settings/'
    | '/projects/$id/databases'
    | '/projects/$id/new'
    | '/projects/$id/pipelines'
    | '/projects/$id/routes'
    | '/projects/$id/settings'
    | '/projects/$id/'
    | '/projects/$id/services/$serviceId'
    | '/projects/$id/stacks/$stackId'
    | '/projects/$id/jobs/$jobId'
    | '/projects/$id/routes/$routeId'
    | '/projects/$id/volumes/$volumeId'
    | '/projects/$id/jobs/'
    | '/projects/$id/routes/'
    | '/projects/$id/secrets/'
    | '/projects/$id/services/'
    | '/projects/$id/stacks/'
    | '/projects/$id/volumes/'
    | '/projects/$id/services/$serviceId/backups'
    | '/projects/$id/services/$serviceId/config'
    | '/projects/$id/services/$serviceId/logs'
    | '/projects/$id/services/$serviceId/overview'
    | '/projects/$id/services/$serviceId/settings'
    | '/projects/$id/stacks/$stackId/editor'
    | '/projects/$id/stacks/$stackId/services'
    | '/projects/$id/services/$serviceId/'
    | '/projects/$id/stacks/$stackId/'
    | '/projects/$id/services/$serviceId/deployments/$deploymentId'
    | '/projects/$id/services/$serviceId/deployments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/integrations/new'
    | '/nodes/$id'
    | '/projects/new'
    | '/cluster'
    | '/integrations'
    | '/nodes'
    | '/projects'
    | '/settings'
    | '/projects/$id/databases'
    | '/projects/$id/new'
    | '/projects/$id/pipelines'
    | '/projects/$id/settings'
    | '/projects/$id'
    | '/projects/$id/jobs/$jobId'
    | '/projects/$id/routes/$routeId'
    | '/projects/$id/volumes/$volumeId'
    | '/projects/$id/jobs'
    | '/projects/$id/routes'
    | '/projects/$id/secrets'
    | '/projects/$id/services'
    | '/projects/$id/stacks'
    | '/projects/$id/volumes'
    | '/projects/$id/services/$serviceId/backups'
    | '/projects/$id/services/$serviceId/config'
    | '/projects/$id/services/$serviceId/logs'
    | '/projects/$id/services/$serviceId/overview'
    | '/projects/$id/services/$serviceId/settings'
    | '/projects/$id/stacks/$stackId/editor'
    | '/projects/$id/stacks/$stackId/services'
    | '/projects/$id/services/$serviceId'
    | '/projects/$id/stacks/$stackId'
    | '/projects/$id/services/$serviceId/deployments/$deploymentId'
    | '/projects/$id/services/$serviceId/deployments'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/projects/$id'
    | '/_app/integrations/new'
    | '/_app/nodes/$id'
    | '/_app/projects/new'
    | '/_app/cluster/'
    | '/_app/integrations/'
    | '/_app/nodes/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/projects/$id/databases'
    | '/_app/projects/$id/new'
    | '/_app/projects/$id/pipelines'
    | '/_app/projects/$id/routes'
    | '/_app/projects/$id/settings'
    | '/_app/projects/$id/'
    | '/_app/projects/$id/services/$serviceId'
    | '/_app/projects/$id/stacks/$stackId'
    | '/_app/projects/$id/jobs/$jobId'
    | '/_app/projects/$id/routes/$routeId'
    | '/_app/projects/$id/volumes/$volumeId'
    | '/_app/projects/$id/jobs/'
    | '/_app/projects/$id/routes/'
    | '/_app/projects/$id/secrets/'
    | '/_app/projects/$id/services/'
    | '/_app/projects/$id/stacks/'
    | '/_app/projects/$id/volumes/'
    | '/_app/projects/$id/services/$serviceId/backups'
    | '/_app/projects/$id/services/$serviceId/config'
    | '/_app/projects/$id/services/$serviceId/logs'
    | '/_app/projects/$id/services/$serviceId/overview'
    | '/_app/projects/$id/services/$serviceId/settings'
    | '/_app/projects/$id/stacks/$stackId/editor'
    | '/_app/projects/$id/stacks/$stackId/services'
    | '/_app/projects/$id/services/$serviceId/'
    | '/_app/projects/$id/stacks/$stackId/'
    | '/_app/projects/$id/services/$serviceId/deployments/$deploymentId'
    | '/_app/projects/$id/services/$serviceId/deployments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/': {
      id: '/_app/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AppNodesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cluster/': {
      id: '/_app/cluster/'
      path: '/cluster'
      fullPath: '/cluster/'
      preLoaderRoute: typeof AppClusterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/$id': {
      id: '/_app/nodes/$id'
      path: '/nodes/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof AppNodesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/new': {
      id: '/_app/integrations/new'
      path: '/integrations/new'
      fullPath: '/integrations/new'
      preLoaderRoute: typeof AppIntegrationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id/': {
      id: '/_app/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/settings': {
      id: '/_app/projects/$id/settings'
      path: '/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof AppProjectsIdSettingsRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/routes': {
      id: '/_app/projects/$id/routes'
      path: '/routes'
      fullPath: '/projects/$id/routes'
      preLoaderRoute: typeof AppProjectsIdRoutesRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/pipelines': {
      id: '/_app/projects/$id/pipelines'
      path: '/pipelines'
      fullPath: '/projects/$id/pipelines'
      preLoaderRoute: typeof AppProjectsIdPipelinesRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/new': {
      id: '/_app/projects/$id/new'
      path: '/new'
      fullPath: '/projects/$id/new'
      preLoaderRoute: typeof AppProjectsIdNewRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/databases': {
      id: '/_app/projects/$id/databases'
      path: '/databases'
      fullPath: '/projects/$id/databases'
      preLoaderRoute: typeof AppProjectsIdDatabasesRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/volumes/': {
      id: '/_app/projects/$id/volumes/'
      path: '/volumes'
      fullPath: '/projects/$id/volumes/'
      preLoaderRoute: typeof AppProjectsIdVolumesIndexRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/stacks/': {
      id: '/_app/projects/$id/stacks/'
      path: '/stacks'
      fullPath: '/projects/$id/stacks/'
      preLoaderRoute: typeof AppProjectsIdStacksIndexRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/services/': {
      id: '/_app/projects/$id/services/'
      path: '/services'
      fullPath: '/projects/$id/services/'
      preLoaderRoute: typeof AppProjectsIdServicesIndexRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/secrets/': {
      id: '/_app/projects/$id/secrets/'
      path: '/secrets'
      fullPath: '/projects/$id/secrets/'
      preLoaderRoute: typeof AppProjectsIdSecretsIndexRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/routes/': {
      id: '/_app/projects/$id/routes/'
      path: '/'
      fullPath: '/projects/$id/routes/'
      preLoaderRoute: typeof AppProjectsIdRoutesIndexRouteImport
      parentRoute: typeof AppProjectsIdRoutesRoute
    }
    '/_app/projects/$id/jobs/': {
      id: '/_app/projects/$id/jobs/'
      path: '/jobs'
      fullPath: '/projects/$id/jobs/'
      preLoaderRoute: typeof AppProjectsIdJobsIndexRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/volumes/$volumeId': {
      id: '/_app/projects/$id/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/projects/$id/volumes/$volumeId'
      preLoaderRoute: typeof AppProjectsIdVolumesVolumeIdRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/routes/$routeId': {
      id: '/_app/projects/$id/routes/$routeId'
      path: '/$routeId'
      fullPath: '/projects/$id/routes/$routeId'
      preLoaderRoute: typeof AppProjectsIdRoutesRouteIdRouteImport
      parentRoute: typeof AppProjectsIdRoutesRoute
    }
    '/_app/projects/$id/jobs/$jobId': {
      id: '/_app/projects/$id/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/projects/$id/jobs/$jobId'
      preLoaderRoute: typeof AppProjectsIdJobsJobIdRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/stacks/$stackId': {
      id: '/_app/projects/$id/stacks/$stackId'
      path: '/stacks/$stackId'
      fullPath: '/projects/$id/stacks/$stackId'
      preLoaderRoute: typeof AppProjectsIdStacksStackIdRouteRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId': {
      id: '/_app/projects/$id/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/projects/$id/services/$serviceId'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdRouteRouteImport
      parentRoute: typeof AppProjectsIdRouteRoute
    }
    '/_app/projects/$id/stacks/$stackId/': {
      id: '/_app/projects/$id/stacks/$stackId/'
      path: '/'
      fullPath: '/projects/$id/stacks/$stackId/'
      preLoaderRoute: typeof AppProjectsIdStacksStackIdIndexRouteImport
      parentRoute: typeof AppProjectsIdStacksStackIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/': {
      id: '/_app/projects/$id/services/$serviceId/'
      path: '/'
      fullPath: '/projects/$id/services/$serviceId/'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdIndexRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
    '/_app/projects/$id/stacks/$stackId/services': {
      id: '/_app/projects/$id/stacks/$stackId/services'
      path: '/services'
      fullPath: '/projects/$id/stacks/$stackId/services'
      preLoaderRoute: typeof AppProjectsIdStacksStackIdServicesRouteImport
      parentRoute: typeof AppProjectsIdStacksStackIdRouteRoute
    }
    '/_app/projects/$id/stacks/$stackId/editor': {
      id: '/_app/projects/$id/stacks/$stackId/editor'
      path: '/editor'
      fullPath: '/projects/$id/stacks/$stackId/editor'
      preLoaderRoute: typeof AppProjectsIdStacksStackIdEditorRouteImport
      parentRoute: typeof AppProjectsIdStacksStackIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/settings': {
      id: '/_app/projects/$id/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/projects/$id/services/$serviceId/settings'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdSettingsRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/overview': {
      id: '/_app/projects/$id/services/$serviceId/overview'
      path: '/overview'
      fullPath: '/projects/$id/services/$serviceId/overview'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdOverviewRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/logs': {
      id: '/_app/projects/$id/services/$serviceId/logs'
      path: '/logs'
      fullPath: '/projects/$id/services/$serviceId/logs'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdLogsRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/config': {
      id: '/_app/projects/$id/services/$serviceId/config'
      path: '/config'
      fullPath: '/projects/$id/services/$serviceId/config'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdConfigRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/backups': {
      id: '/_app/projects/$id/services/$serviceId/backups'
      path: '/backups'
      fullPath: '/projects/$id/services/$serviceId/backups'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdBackupsRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/deployments/': {
      id: '/_app/projects/$id/services/$serviceId/deployments/'
      path: '/deployments'
      fullPath: '/projects/$id/services/$serviceId/deployments/'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdDeploymentsIndexRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
    '/_app/projects/$id/services/$serviceId/deployments/$deploymentId': {
      id: '/_app/projects/$id/services/$serviceId/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/projects/$id/services/$serviceId/deployments/$deploymentId'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRouteRoute
    }
  }
}

interface AppProjectsIdRoutesRouteChildren {
  AppProjectsIdRoutesRouteIdRoute: typeof AppProjectsIdRoutesRouteIdRoute
  AppProjectsIdRoutesIndexRoute: typeof AppProjectsIdRoutesIndexRoute
}

const AppProjectsIdRoutesRouteChildren: AppProjectsIdRoutesRouteChildren = {
  AppProjectsIdRoutesRouteIdRoute: AppProjectsIdRoutesRouteIdRoute,
  AppProjectsIdRoutesIndexRoute: AppProjectsIdRoutesIndexRoute,
}

const AppProjectsIdRoutesRouteWithChildren =
  AppProjectsIdRoutesRoute._addFileChildren(AppProjectsIdRoutesRouteChildren)

interface AppProjectsIdServicesServiceIdRouteRouteChildren {
  AppProjectsIdServicesServiceIdBackupsRoute: typeof AppProjectsIdServicesServiceIdBackupsRoute
  AppProjectsIdServicesServiceIdConfigRoute: typeof AppProjectsIdServicesServiceIdConfigRoute
  AppProjectsIdServicesServiceIdLogsRoute: typeof AppProjectsIdServicesServiceIdLogsRoute
  AppProjectsIdServicesServiceIdOverviewRoute: typeof AppProjectsIdServicesServiceIdOverviewRoute
  AppProjectsIdServicesServiceIdSettingsRoute: typeof AppProjectsIdServicesServiceIdSettingsRoute
  AppProjectsIdServicesServiceIdIndexRoute: typeof AppProjectsIdServicesServiceIdIndexRoute
  AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute: typeof AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute
  AppProjectsIdServicesServiceIdDeploymentsIndexRoute: typeof AppProjectsIdServicesServiceIdDeploymentsIndexRoute
}

const AppProjectsIdServicesServiceIdRouteRouteChildren: AppProjectsIdServicesServiceIdRouteRouteChildren =
  {
    AppProjectsIdServicesServiceIdBackupsRoute:
      AppProjectsIdServicesServiceIdBackupsRoute,
    AppProjectsIdServicesServiceIdConfigRoute:
      AppProjectsIdServicesServiceIdConfigRoute,
    AppProjectsIdServicesServiceIdLogsRoute:
      AppProjectsIdServicesServiceIdLogsRoute,
    AppProjectsIdServicesServiceIdOverviewRoute:
      AppProjectsIdServicesServiceIdOverviewRoute,
    AppProjectsIdServicesServiceIdSettingsRoute:
      AppProjectsIdServicesServiceIdSettingsRoute,
    AppProjectsIdServicesServiceIdIndexRoute:
      AppProjectsIdServicesServiceIdIndexRoute,
    AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute:
      AppProjectsIdServicesServiceIdDeploymentsDeploymentIdRoute,
    AppProjectsIdServicesServiceIdDeploymentsIndexRoute:
      AppProjectsIdServicesServiceIdDeploymentsIndexRoute,
  }

const AppProjectsIdServicesServiceIdRouteRouteWithChildren =
  AppProjectsIdServicesServiceIdRouteRoute._addFileChildren(
    AppProjectsIdServicesServiceIdRouteRouteChildren,
  )

interface AppProjectsIdStacksStackIdRouteRouteChildren {
  AppProjectsIdStacksStackIdEditorRoute: typeof AppProjectsIdStacksStackIdEditorRoute
  AppProjectsIdStacksStackIdServicesRoute: typeof AppProjectsIdStacksStackIdServicesRoute
  AppProjectsIdStacksStackIdIndexRoute: typeof AppProjectsIdStacksStackIdIndexRoute
}

const AppProjectsIdStacksStackIdRouteRouteChildren: AppProjectsIdStacksStackIdRouteRouteChildren =
  {
    AppProjectsIdStacksStackIdEditorRoute:
      AppProjectsIdStacksStackIdEditorRoute,
    AppProjectsIdStacksStackIdServicesRoute:
      AppProjectsIdStacksStackIdServicesRoute,
    AppProjectsIdStacksStackIdIndexRoute: AppProjectsIdStacksStackIdIndexRoute,
  }

const AppProjectsIdStacksStackIdRouteRouteWithChildren =
  AppProjectsIdStacksStackIdRouteRoute._addFileChildren(
    AppProjectsIdStacksStackIdRouteRouteChildren,
  )

interface AppProjectsIdRouteRouteChildren {
  AppProjectsIdDatabasesRoute: typeof AppProjectsIdDatabasesRoute
  AppProjectsIdNewRoute: typeof AppProjectsIdNewRoute
  AppProjectsIdPipelinesRoute: typeof AppProjectsIdPipelinesRoute
  AppProjectsIdRoutesRoute: typeof AppProjectsIdRoutesRouteWithChildren
  AppProjectsIdSettingsRoute: typeof AppProjectsIdSettingsRoute
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
  AppProjectsIdServicesServiceIdRouteRoute: typeof AppProjectsIdServicesServiceIdRouteRouteWithChildren
  AppProjectsIdStacksStackIdRouteRoute: typeof AppProjectsIdStacksStackIdRouteRouteWithChildren
  AppProjectsIdJobsJobIdRoute: typeof AppProjectsIdJobsJobIdRoute
  AppProjectsIdVolumesVolumeIdRoute: typeof AppProjectsIdVolumesVolumeIdRoute
  AppProjectsIdJobsIndexRoute: typeof AppProjectsIdJobsIndexRoute
  AppProjectsIdSecretsIndexRoute: typeof AppProjectsIdSecretsIndexRoute
  AppProjectsIdServicesIndexRoute: typeof AppProjectsIdServicesIndexRoute
  AppProjectsIdStacksIndexRoute: typeof AppProjectsIdStacksIndexRoute
  AppProjectsIdVolumesIndexRoute: typeof AppProjectsIdVolumesIndexRoute
}

const AppProjectsIdRouteRouteChildren: AppProjectsIdRouteRouteChildren = {
  AppProjectsIdDatabasesRoute: AppProjectsIdDatabasesRoute,
  AppProjectsIdNewRoute: AppProjectsIdNewRoute,
  AppProjectsIdPipelinesRoute: AppProjectsIdPipelinesRoute,
  AppProjectsIdRoutesRoute: AppProjectsIdRoutesRouteWithChildren,
  AppProjectsIdSettingsRoute: AppProjectsIdSettingsRoute,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
  AppProjectsIdServicesServiceIdRouteRoute:
    AppProjectsIdServicesServiceIdRouteRouteWithChildren,
  AppProjectsIdStacksStackIdRouteRoute:
    AppProjectsIdStacksStackIdRouteRouteWithChildren,
  AppProjectsIdJobsJobIdRoute: AppProjectsIdJobsJobIdRoute,
  AppProjectsIdVolumesVolumeIdRoute: AppProjectsIdVolumesVolumeIdRoute,
  AppProjectsIdJobsIndexRoute: AppProjectsIdJobsIndexRoute,
  AppProjectsIdSecretsIndexRoute: AppProjectsIdSecretsIndexRoute,
  AppProjectsIdServicesIndexRoute: AppProjectsIdServicesIndexRoute,
  AppProjectsIdStacksIndexRoute: AppProjectsIdStacksIndexRoute,
  AppProjectsIdVolumesIndexRoute: AppProjectsIdVolumesIndexRoute,
}

const AppProjectsIdRouteRouteWithChildren =
  AppProjectsIdRouteRoute._addFileChildren(AppProjectsIdRouteRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsIdRouteRoute: typeof AppProjectsIdRouteRouteWithChildren
  AppIntegrationsNewRoute: typeof AppIntegrationsNewRoute
  AppNodesIdRoute: typeof AppNodesIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppClusterIndexRoute: typeof AppClusterIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppNodesIndexRoute: typeof AppNodesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectsIdRouteRoute: AppProjectsIdRouteRouteWithChildren,
  AppIntegrationsNewRoute: AppIntegrationsNewRoute,
  AppNodesIdRoute: AppNodesIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppClusterIndexRoute: AppClusterIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppNodesIndexRoute: AppNodesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
