/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppNodesIndexRouteImport } from './routes/_app/nodes/index'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app/integrations/index'
import { Route as AppClusterIndexRouteImport } from './routes/_app/cluster/index'
import { Route as AppNodesIdRouteImport } from './routes/_app/nodes/$id'
import { Route as AppDomainsNewRouteImport } from './routes/_app/domains/new'
import { Route as AppProjectsIdIndexRouteImport } from './routes/_app/projects/$id/index'
import { Route as AppProjectsIdNewServiceRouteImport } from './routes/_app/projects/$id/new-service'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIndexRoute = AppNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const AppClusterIndexRoute = AppClusterIndexRouteImport.update({
  id: '/cluster/',
  path: '/cluster/',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIdRoute = AppNodesIdRouteImport.update({
  id: '/nodes/$id',
  path: '/nodes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsNewRoute = AppDomainsNewRouteImport.update({
  id: '/domains/new',
  path: '/domains/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdNewServiceRoute = AppProjectsIdNewServiceRouteImport.update({
  id: '/projects/$id/new-service',
  path: '/projects/$id/new-service',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/domains/new': typeof AppDomainsNewRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/cluster/': typeof AppClusterIndexRoute
  '/integrations/': typeof AppIntegrationsIndexRoute
  '/nodes/': typeof AppNodesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/projects/$id/new-service': typeof AppProjectsIdNewServiceRoute
  '/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/domains/new': typeof AppDomainsNewRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/cluster': typeof AppClusterIndexRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/nodes': typeof AppNodesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/projects/$id/new-service': typeof AppProjectsIdNewServiceRoute
  '/projects/$id': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/domains/new': typeof AppDomainsNewRoute
  '/_app/nodes/$id': typeof AppNodesIdRoute
  '/_app/cluster/': typeof AppClusterIndexRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/nodes/': typeof AppNodesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/projects/$id/new-service': typeof AppProjectsIdNewServiceRoute
  '/_app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/domains/new'
    | '/nodes/$id'
    | '/cluster/'
    | '/integrations/'
    | '/nodes/'
    | '/projects/'
    | '/settings/'
    | '/projects/$id/new-service'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/domains/new'
    | '/nodes/$id'
    | '/cluster'
    | '/integrations'
    | '/nodes'
    | '/projects'
    | '/settings'
    | '/projects/$id/new-service'
    | '/projects/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/domains/new'
    | '/_app/nodes/$id'
    | '/_app/cluster/'
    | '/_app/integrations/'
    | '/_app/nodes/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/projects/$id/new-service'
    | '/_app/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/': {
      id: '/_app/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AppNodesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cluster/': {
      id: '/_app/cluster/'
      path: '/cluster'
      fullPath: '/cluster/'
      preLoaderRoute: typeof AppClusterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/$id': {
      id: '/_app/nodes/$id'
      path: '/nodes/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof AppNodesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains/new': {
      id: '/_app/domains/new'
      path: '/domains/new'
      fullPath: '/domains/new'
      preLoaderRoute: typeof AppDomainsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id/': {
      id: '/_app/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id/new-service': {
      id: '/_app/projects/$id/new-service'
      path: '/projects/$id/new-service'
      fullPath: '/projects/$id/new-service'
      preLoaderRoute: typeof AppProjectsIdNewServiceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDomainsNewRoute: typeof AppDomainsNewRoute
  AppNodesIdRoute: typeof AppNodesIdRoute
  AppClusterIndexRoute: typeof AppClusterIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppNodesIndexRoute: typeof AppNodesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppProjectsIdNewServiceRoute: typeof AppProjectsIdNewServiceRoute
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDomainsNewRoute: AppDomainsNewRoute,
  AppNodesIdRoute: AppNodesIdRoute,
  AppClusterIndexRoute: AppClusterIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppNodesIndexRoute: AppNodesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppProjectsIdNewServiceRoute: AppProjectsIdNewServiceRoute,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
