/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppNodesIndexRouteImport } from './routes/_app/nodes/index'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app/integrations/index'
import { Route as AppClusterIndexRouteImport } from './routes/_app/cluster/index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects/$id'
import { Route as AppNodesIdRouteImport } from './routes/_app/nodes/$id'
import { Route as AppDomainsNewRouteImport } from './routes/_app/domains/new'
import { Route as AppProjectsIdIndexRouteImport } from './routes/_app/projects/$id/index'
import { Route as AppProjectsIdSettingsRouteImport } from './routes/_app/projects/$id/settings'
import { Route as AppProjectsIdServicesRouteImport } from './routes/_app/projects/$id/services'
import { Route as AppProjectsIdRoutesRouteImport } from './routes/_app/projects/$id/routes'
import { Route as AppProjectsIdPipelinesRouteImport } from './routes/_app/projects/$id/pipelines'
import { Route as AppProjectsIdNewServiceRouteImport } from './routes/_app/projects/$id/new-service'
import { Route as AppProjectsIdNewRouteImport } from './routes/_app/projects/$id/new'
import { Route as AppProjectsIdJobsRouteImport } from './routes/_app/projects/$id/jobs'
import { Route as AppProjectsIdDatabasesRouteImport } from './routes/_app/projects/$id/databases'
import { Route as AppProjectsIdCronJobsRouteImport } from './routes/_app/projects/$id/cron-jobs'
import { Route as AppProjectsIdServicesServiceIdRouteImport } from './routes/_app/projects/$id/services/$serviceId'
import { Route as AppProjectsIdServicesServiceIdIndexRouteImport } from './routes/_app/projects/$id/services/$serviceId/index'
import { Route as AppProjectsIdServicesServiceIdSettingsRouteImport } from './routes/_app/projects/$id/services/$serviceId/settings'
import { Route as AppProjectsIdServicesServiceIdLogsRouteImport } from './routes/_app/projects/$id/services/$serviceId/logs'
import { Route as AppProjectsIdServicesServiceIdDeploymentsRouteImport } from './routes/_app/projects/$id/services/$serviceId/deployments'
import { Route as AppProjectsIdServicesServiceIdConfigRouteImport } from './routes/_app/projects/$id/services/$serviceId/config'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIndexRoute = AppNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const AppClusterIndexRoute = AppClusterIndexRouteImport.update({
  id: '/cluster/',
  path: '/cluster/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIdRoute = AppNodesIdRouteImport.update({
  id: '/nodes/$id',
  path: '/nodes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsNewRoute = AppDomainsNewRouteImport.update({
  id: '/domains/new',
  path: '/domains/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdSettingsRoute = AppProjectsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdServicesRoute = AppProjectsIdServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdRoutesRoute = AppProjectsIdRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdPipelinesRoute = AppProjectsIdPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdNewServiceRoute = AppProjectsIdNewServiceRouteImport.update({
  id: '/new-service',
  path: '/new-service',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdNewRoute = AppProjectsIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdJobsRoute = AppProjectsIdJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdDatabasesRoute = AppProjectsIdDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdCronJobsRoute = AppProjectsIdCronJobsRouteImport.update({
  id: '/cron-jobs',
  path: '/cron-jobs',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdServicesServiceIdRoute =
  AppProjectsIdServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => AppProjectsIdServicesRoute,
  } as any)
const AppProjectsIdServicesServiceIdIndexRoute =
  AppProjectsIdServicesServiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdServicesServiceIdRoute,
  } as any)
const AppProjectsIdServicesServiceIdSettingsRoute =
  AppProjectsIdServicesServiceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsIdServicesServiceIdRoute,
  } as any)
const AppProjectsIdServicesServiceIdLogsRoute =
  AppProjectsIdServicesServiceIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsIdServicesServiceIdRoute,
  } as any)
const AppProjectsIdServicesServiceIdDeploymentsRoute =
  AppProjectsIdServicesServiceIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppProjectsIdServicesServiceIdRoute,
  } as any)
const AppProjectsIdServicesServiceIdConfigRoute =
  AppProjectsIdServicesServiceIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AppProjectsIdServicesServiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/domains/new': typeof AppDomainsNewRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/cluster/': typeof AppClusterIndexRoute
  '/integrations/': typeof AppIntegrationsIndexRoute
  '/nodes/': typeof AppNodesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/projects/$id/cron-jobs': typeof AppProjectsIdCronJobsRoute
  '/projects/$id/databases': typeof AppProjectsIdDatabasesRoute
  '/projects/$id/jobs': typeof AppProjectsIdJobsRoute
  '/projects/$id/new': typeof AppProjectsIdNewRoute
  '/projects/$id/new-service': typeof AppProjectsIdNewServiceRoute
  '/projects/$id/pipelines': typeof AppProjectsIdPipelinesRoute
  '/projects/$id/routes': typeof AppProjectsIdRoutesRoute
  '/projects/$id/services': typeof AppProjectsIdServicesRouteWithChildren
  '/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/projects/$id/': typeof AppProjectsIdIndexRoute
  '/projects/$id/services/$serviceId': typeof AppProjectsIdServicesServiceIdRouteWithChildren
  '/projects/$id/services/$serviceId/config': typeof AppProjectsIdServicesServiceIdConfigRoute
  '/projects/$id/services/$serviceId/deployments': typeof AppProjectsIdServicesServiceIdDeploymentsRoute
  '/projects/$id/services/$serviceId/logs': typeof AppProjectsIdServicesServiceIdLogsRoute
  '/projects/$id/services/$serviceId/settings': typeof AppProjectsIdServicesServiceIdSettingsRoute
  '/projects/$id/services/$serviceId/': typeof AppProjectsIdServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/domains/new': typeof AppDomainsNewRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/cluster': typeof AppClusterIndexRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/nodes': typeof AppNodesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/projects/$id/cron-jobs': typeof AppProjectsIdCronJobsRoute
  '/projects/$id/databases': typeof AppProjectsIdDatabasesRoute
  '/projects/$id/jobs': typeof AppProjectsIdJobsRoute
  '/projects/$id/new': typeof AppProjectsIdNewRoute
  '/projects/$id/new-service': typeof AppProjectsIdNewServiceRoute
  '/projects/$id/pipelines': typeof AppProjectsIdPipelinesRoute
  '/projects/$id/routes': typeof AppProjectsIdRoutesRoute
  '/projects/$id/services': typeof AppProjectsIdServicesRouteWithChildren
  '/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/projects/$id': typeof AppProjectsIdIndexRoute
  '/projects/$id/services/$serviceId/config': typeof AppProjectsIdServicesServiceIdConfigRoute
  '/projects/$id/services/$serviceId/deployments': typeof AppProjectsIdServicesServiceIdDeploymentsRoute
  '/projects/$id/services/$serviceId/logs': typeof AppProjectsIdServicesServiceIdLogsRoute
  '/projects/$id/services/$serviceId/settings': typeof AppProjectsIdServicesServiceIdSettingsRoute
  '/projects/$id/services/$serviceId': typeof AppProjectsIdServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/domains/new': typeof AppDomainsNewRoute
  '/_app/nodes/$id': typeof AppNodesIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/_app/cluster/': typeof AppClusterIndexRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/nodes/': typeof AppNodesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/projects/$id/cron-jobs': typeof AppProjectsIdCronJobsRoute
  '/_app/projects/$id/databases': typeof AppProjectsIdDatabasesRoute
  '/_app/projects/$id/jobs': typeof AppProjectsIdJobsRoute
  '/_app/projects/$id/new': typeof AppProjectsIdNewRoute
  '/_app/projects/$id/new-service': typeof AppProjectsIdNewServiceRoute
  '/_app/projects/$id/pipelines': typeof AppProjectsIdPipelinesRoute
  '/_app/projects/$id/routes': typeof AppProjectsIdRoutesRoute
  '/_app/projects/$id/services': typeof AppProjectsIdServicesRouteWithChildren
  '/_app/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/_app/projects/$id/': typeof AppProjectsIdIndexRoute
  '/_app/projects/$id/services/$serviceId': typeof AppProjectsIdServicesServiceIdRouteWithChildren
  '/_app/projects/$id/services/$serviceId/config': typeof AppProjectsIdServicesServiceIdConfigRoute
  '/_app/projects/$id/services/$serviceId/deployments': typeof AppProjectsIdServicesServiceIdDeploymentsRoute
  '/_app/projects/$id/services/$serviceId/logs': typeof AppProjectsIdServicesServiceIdLogsRoute
  '/_app/projects/$id/services/$serviceId/settings': typeof AppProjectsIdServicesServiceIdSettingsRoute
  '/_app/projects/$id/services/$serviceId/': typeof AppProjectsIdServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/domains/new'
    | '/nodes/$id'
    | '/projects/$id'
    | '/cluster/'
    | '/integrations/'
    | '/nodes/'
    | '/projects/'
    | '/settings/'
    | '/projects/$id/cron-jobs'
    | '/projects/$id/databases'
    | '/projects/$id/jobs'
    | '/projects/$id/new'
    | '/projects/$id/new-service'
    | '/projects/$id/pipelines'
    | '/projects/$id/routes'
    | '/projects/$id/services'
    | '/projects/$id/settings'
    | '/projects/$id/'
    | '/projects/$id/services/$serviceId'
    | '/projects/$id/services/$serviceId/config'
    | '/projects/$id/services/$serviceId/deployments'
    | '/projects/$id/services/$serviceId/logs'
    | '/projects/$id/services/$serviceId/settings'
    | '/projects/$id/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/domains/new'
    | '/nodes/$id'
    | '/cluster'
    | '/integrations'
    | '/nodes'
    | '/projects'
    | '/settings'
    | '/projects/$id/cron-jobs'
    | '/projects/$id/databases'
    | '/projects/$id/jobs'
    | '/projects/$id/new'
    | '/projects/$id/new-service'
    | '/projects/$id/pipelines'
    | '/projects/$id/routes'
    | '/projects/$id/services'
    | '/projects/$id/settings'
    | '/projects/$id'
    | '/projects/$id/services/$serviceId/config'
    | '/projects/$id/services/$serviceId/deployments'
    | '/projects/$id/services/$serviceId/logs'
    | '/projects/$id/services/$serviceId/settings'
    | '/projects/$id/services/$serviceId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/domains/new'
    | '/_app/nodes/$id'
    | '/_app/projects/$id'
    | '/_app/cluster/'
    | '/_app/integrations/'
    | '/_app/nodes/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/projects/$id/cron-jobs'
    | '/_app/projects/$id/databases'
    | '/_app/projects/$id/jobs'
    | '/_app/projects/$id/new'
    | '/_app/projects/$id/new-service'
    | '/_app/projects/$id/pipelines'
    | '/_app/projects/$id/routes'
    | '/_app/projects/$id/services'
    | '/_app/projects/$id/settings'
    | '/_app/projects/$id/'
    | '/_app/projects/$id/services/$serviceId'
    | '/_app/projects/$id/services/$serviceId/config'
    | '/_app/projects/$id/services/$serviceId/deployments'
    | '/_app/projects/$id/services/$serviceId/logs'
    | '/_app/projects/$id/services/$serviceId/settings'
    | '/_app/projects/$id/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/': {
      id: '/_app/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AppNodesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cluster/': {
      id: '/_app/cluster/'
      path: '/cluster'
      fullPath: '/cluster/'
      preLoaderRoute: typeof AppClusterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/$id': {
      id: '/_app/nodes/$id'
      path: '/nodes/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof AppNodesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains/new': {
      id: '/_app/domains/new'
      path: '/domains/new'
      fullPath: '/domains/new'
      preLoaderRoute: typeof AppDomainsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id/': {
      id: '/_app/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/settings': {
      id: '/_app/projects/$id/settings'
      path: '/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof AppProjectsIdSettingsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/services': {
      id: '/_app/projects/$id/services'
      path: '/services'
      fullPath: '/projects/$id/services'
      preLoaderRoute: typeof AppProjectsIdServicesRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/routes': {
      id: '/_app/projects/$id/routes'
      path: '/routes'
      fullPath: '/projects/$id/routes'
      preLoaderRoute: typeof AppProjectsIdRoutesRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/pipelines': {
      id: '/_app/projects/$id/pipelines'
      path: '/pipelines'
      fullPath: '/projects/$id/pipelines'
      preLoaderRoute: typeof AppProjectsIdPipelinesRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/new-service': {
      id: '/_app/projects/$id/new-service'
      path: '/new-service'
      fullPath: '/projects/$id/new-service'
      preLoaderRoute: typeof AppProjectsIdNewServiceRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/new': {
      id: '/_app/projects/$id/new'
      path: '/new'
      fullPath: '/projects/$id/new'
      preLoaderRoute: typeof AppProjectsIdNewRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/jobs': {
      id: '/_app/projects/$id/jobs'
      path: '/jobs'
      fullPath: '/projects/$id/jobs'
      preLoaderRoute: typeof AppProjectsIdJobsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/databases': {
      id: '/_app/projects/$id/databases'
      path: '/databases'
      fullPath: '/projects/$id/databases'
      preLoaderRoute: typeof AppProjectsIdDatabasesRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/cron-jobs': {
      id: '/_app/projects/$id/cron-jobs'
      path: '/cron-jobs'
      fullPath: '/projects/$id/cron-jobs'
      preLoaderRoute: typeof AppProjectsIdCronJobsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/services/$serviceId': {
      id: '/_app/projects/$id/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/projects/$id/services/$serviceId'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdRouteImport
      parentRoute: typeof AppProjectsIdServicesRoute
    }
    '/_app/projects/$id/services/$serviceId/': {
      id: '/_app/projects/$id/services/$serviceId/'
      path: '/'
      fullPath: '/projects/$id/services/$serviceId/'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdIndexRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRoute
    }
    '/_app/projects/$id/services/$serviceId/settings': {
      id: '/_app/projects/$id/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/projects/$id/services/$serviceId/settings'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdSettingsRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRoute
    }
    '/_app/projects/$id/services/$serviceId/logs': {
      id: '/_app/projects/$id/services/$serviceId/logs'
      path: '/logs'
      fullPath: '/projects/$id/services/$serviceId/logs'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdLogsRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRoute
    }
    '/_app/projects/$id/services/$serviceId/deployments': {
      id: '/_app/projects/$id/services/$serviceId/deployments'
      path: '/deployments'
      fullPath: '/projects/$id/services/$serviceId/deployments'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdDeploymentsRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRoute
    }
    '/_app/projects/$id/services/$serviceId/config': {
      id: '/_app/projects/$id/services/$serviceId/config'
      path: '/config'
      fullPath: '/projects/$id/services/$serviceId/config'
      preLoaderRoute: typeof AppProjectsIdServicesServiceIdConfigRouteImport
      parentRoute: typeof AppProjectsIdServicesServiceIdRoute
    }
  }
}

interface AppProjectsIdServicesServiceIdRouteChildren {
  AppProjectsIdServicesServiceIdConfigRoute: typeof AppProjectsIdServicesServiceIdConfigRoute
  AppProjectsIdServicesServiceIdDeploymentsRoute: typeof AppProjectsIdServicesServiceIdDeploymentsRoute
  AppProjectsIdServicesServiceIdLogsRoute: typeof AppProjectsIdServicesServiceIdLogsRoute
  AppProjectsIdServicesServiceIdSettingsRoute: typeof AppProjectsIdServicesServiceIdSettingsRoute
  AppProjectsIdServicesServiceIdIndexRoute: typeof AppProjectsIdServicesServiceIdIndexRoute
}

const AppProjectsIdServicesServiceIdRouteChildren: AppProjectsIdServicesServiceIdRouteChildren =
  {
    AppProjectsIdServicesServiceIdConfigRoute:
      AppProjectsIdServicesServiceIdConfigRoute,
    AppProjectsIdServicesServiceIdDeploymentsRoute:
      AppProjectsIdServicesServiceIdDeploymentsRoute,
    AppProjectsIdServicesServiceIdLogsRoute:
      AppProjectsIdServicesServiceIdLogsRoute,
    AppProjectsIdServicesServiceIdSettingsRoute:
      AppProjectsIdServicesServiceIdSettingsRoute,
    AppProjectsIdServicesServiceIdIndexRoute:
      AppProjectsIdServicesServiceIdIndexRoute,
  }

const AppProjectsIdServicesServiceIdRouteWithChildren =
  AppProjectsIdServicesServiceIdRoute._addFileChildren(
    AppProjectsIdServicesServiceIdRouteChildren,
  )

interface AppProjectsIdServicesRouteChildren {
  AppProjectsIdServicesServiceIdRoute: typeof AppProjectsIdServicesServiceIdRouteWithChildren
}

const AppProjectsIdServicesRouteChildren: AppProjectsIdServicesRouteChildren = {
  AppProjectsIdServicesServiceIdRoute:
    AppProjectsIdServicesServiceIdRouteWithChildren,
}

const AppProjectsIdServicesRouteWithChildren =
  AppProjectsIdServicesRoute._addFileChildren(
    AppProjectsIdServicesRouteChildren,
  )

interface AppProjectsIdRouteChildren {
  AppProjectsIdCronJobsRoute: typeof AppProjectsIdCronJobsRoute
  AppProjectsIdDatabasesRoute: typeof AppProjectsIdDatabasesRoute
  AppProjectsIdJobsRoute: typeof AppProjectsIdJobsRoute
  AppProjectsIdNewRoute: typeof AppProjectsIdNewRoute
  AppProjectsIdNewServiceRoute: typeof AppProjectsIdNewServiceRoute
  AppProjectsIdPipelinesRoute: typeof AppProjectsIdPipelinesRoute
  AppProjectsIdRoutesRoute: typeof AppProjectsIdRoutesRoute
  AppProjectsIdServicesRoute: typeof AppProjectsIdServicesRouteWithChildren
  AppProjectsIdSettingsRoute: typeof AppProjectsIdSettingsRoute
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdCronJobsRoute: AppProjectsIdCronJobsRoute,
  AppProjectsIdDatabasesRoute: AppProjectsIdDatabasesRoute,
  AppProjectsIdJobsRoute: AppProjectsIdJobsRoute,
  AppProjectsIdNewRoute: AppProjectsIdNewRoute,
  AppProjectsIdNewServiceRoute: AppProjectsIdNewServiceRoute,
  AppProjectsIdPipelinesRoute: AppProjectsIdPipelinesRoute,
  AppProjectsIdRoutesRoute: AppProjectsIdRoutesRoute,
  AppProjectsIdServicesRoute: AppProjectsIdServicesRouteWithChildren,
  AppProjectsIdSettingsRoute: AppProjectsIdSettingsRoute,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDomainsNewRoute: typeof AppDomainsNewRoute
  AppNodesIdRoute: typeof AppNodesIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
  AppClusterIndexRoute: typeof AppClusterIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppNodesIndexRoute: typeof AppNodesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDomainsNewRoute: AppDomainsNewRoute,
  AppNodesIdRoute: AppNodesIdRoute,
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
  AppClusterIndexRoute: AppClusterIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppNodesIndexRoute: AppNodesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
