#!/usr/bin/env bash
# Exercises the parts of deploy/install.sh that decide what a *re-run* does to
# a server that is already installed.
#
# This is not a style check. Re-running the installer used to mint a new
# POSTGRES_PASSWORD, ENCRYPTION_KEY and JWT_SECRET and rewrite .env from a fixed
# list, which leaves the API unable to log in to its own database, every stored
# credential unreadable, and an Enterprise server back on the Community images.
# None of that is visible from reading the script, and the only other way to
# find it is on a real server, so the behaviour is pinned here.
#
# The helpers are sourced out of install.sh rather than copied, so a change to
# them is a change to what this tests.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Everything from read_env down to the next section of the installer.
awk '/^# read_env <key>/, /^# port_in_use <port>/' "$ROOT/deploy/install.sh" \
  | sed '$d' > "$WORK/helpers.sh"
grep -q 'set_env()' "$WORK/helpers.sh" || { echo "could not extract the helpers from install.sh"; exit 1; }

cd "$WORK"
# shellcheck disable=SC1091
source ./helpers.sh

fail=0
check() {
  if [[ "$2" == "$3" ]]; then
    echo "  ok   $1"
  else
    echo "  FAIL $1: got [$2] want [$3]"
    fail=1
  fi
}

# An installed Enterprise server, pinned to the edge channel, with a Headscale
# API key someone filled in by hand.
cat > .env <<'ENV'
DOMAIN=old.example.com
POSTGRES_PASSWORD=keepme-pg
JWT_SECRET=keepme-jwt
ENCRYPTION_KEY=keepme-enc
SETUP_TOKEN=ms_abc
MESHPLOY_CHANNEL=main
MESHPLOY_API_IMAGE=ghcr.io/meshploy/api-ee:latest
MESHPLOY_WEB_IMAGE=ghcr.io/meshploy/web-ee:latest
GHCR_USER=someone
HEADSCALE_API_KEY=filled-in-by-hand
ENV

echo "the installer reads the secrets back instead of generating new ones"
check "postgres password" "$(read_env POSTGRES_PASSWORD)" "keepme-pg"
check "encryption key"    "$(read_env ENCRYPTION_KEY)"    "keepme-enc"
check "a missing key is empty, not an error" "$(read_env NOPE)" ""

echo "a re-run updates what it owns and leaves the rest"
set_env DOMAIN "new.example.com"
set_env K3S_TOKEN "K10abc::server:sec/ret+with|delimiters"
set_env FIREWALL_STATE "ufw"
grep -q '^HEADSCALE_API_KEY=' .env || set_env HEADSCALE_API_KEY ""

check "domain updated"                "$(read_env DOMAIN)"             "new.example.com"
check "a value with delimiters survives" "$(read_env K3S_TOKEN)"       "K10abc::server:sec/ret+with|delimiters"
check "an absent key is appended"     "$(read_env FIREWALL_STATE)"     "ufw"
check "Enterprise api image kept"     "$(read_env MESHPLOY_API_IMAGE)" "ghcr.io/meshploy/api-ee:latest"
check "Enterprise web image kept"     "$(read_env MESHPLOY_WEB_IMAGE)" "ghcr.io/meshploy/web-ee:latest"
check "registry user kept"            "$(read_env GHCR_USER)"          "someone"
check "edge channel not reset"        "$(read_env MESHPLOY_CHANNEL)"   "main"
check "secrets untouched"             "$(read_env JWT_SECRET)"         "keepme-jwt"
check "hand-filled key not blanked"   "$(read_env HEADSCALE_API_KEY)"  "filled-in-by-hand"
check ".env stays readable by root alone" "$(stat -c %a .env)"         "600"
check "no temporary copy left behind" "$(ls .env.?????? 2>/dev/null | wc -l)" "0"

# The CoreDNS and Headscale configs used to be rendered here, from templates
# substituted with DOMAIN. They are generated by `meshploy domain apply` now,
# and tested with its golden files in apps/cli/internal/edgeconfig.

if [[ $fail -eq 0 ]]; then
  echo "install.sh re-run behaviour: ok"
else
  echo "install.sh re-run behaviour: FAILURES"
  exit 1
fi
